// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbAbogadosJueces
    {
        public TbAbogadosJueces()
        {
            TbCasosCasoAbogadoDemandadoNavigation = new HashSet<TbCasos>();
            TbCasosCasoAbogadoDemandanteNavigation = new HashSet<TbCasos>();
            TbCasosCasoJuezNavigation = new HashSet<TbCasos>();
        }

        public int AbjuId { get; set; }
        public string AbjuDni { get; set; }
        public string AbjuNombres { get; set; }
        public string AbjuApellidos { get; set; }
        public string AbjuSexo { get; set; }
        public string AbjuTelefono { get; set; }
        public string AbjuCorreoElectronico { get; set; }
        public DateTime AbjuFechaNacimiento { get; set; }
        public int EcivId { get; set; }
        public int CargId { get; set; }
        public string MuniId { get; set; }
        public string AbjuDireccion { get; set; }
        public int AbjuUsuCreacion { get; set; }
        public DateTime AbjuFechaCreacion { get; set; }
        public int? AbjuUsuModificacion { get; set; }
        public DateTime? AbjuFechaModificacion { get; set; }
        public bool? AbjuEstado { get; set; }

        public virtual TbUsuarios AbjuUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios AbjuUsuModificacionNavigation { get; set; }
        public virtual TbCargos Carg { get; set; }
        public virtual TbEstadosCiviles Eciv { get; set; }
        public virtual TbMunicipios Muni { get; set; }
        public virtual ICollection<TbCasos> TbCasosCasoAbogadoDemandadoNavigation { get; set; }
        public virtual ICollection<TbCasos> TbCasosCasoAbogadoDemandanteNavigation { get; set; }
        public virtual ICollection<TbCasos> TbCasosCasoJuezNavigation { get; set; }
    }
}