// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbAcusadoPorCaso
    {
        public int AcusId { get; set; }
        public int? CasoId { get; set; }
        public int? AcusTipoAcusado { get; set; }
        public int? AcusAcusado { get; set; }
        public int AcusUsuCreacion { get; set; }
        public DateTime AcusFechaCreacion { get; set; }
        public int? AcusUsuModificacion { get; set; }
        public DateTime? AcusFechaModificacion { get; set; }
        public bool? AcusEstado { get; set; }

        public virtual TbUsuarios AcusUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios AcusUsuModificacionNavigation { get; set; }
        public virtual TbCasos Caso { get; set; }
    }
}