// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbCargos
    {
        public TbCargos()
        {
            TbAbogadosJueces = new HashSet<TbAbogadosJueces>();
        }

        public int CargId { get; set; }
        public string CargDescripcion { get; set; }
        public int CargUsuCreacion { get; set; }
        public DateTime? CargFechaCreacion { get; set; }
        public int? CargUsuModificacion { get; set; }
        public DateTime? CargFechaModificacion { get; set; }
        public bool? CargEstado { get; set; }

        public virtual TbUsuarios CargUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios CargUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbAbogadosJueces> TbAbogadosJueces { get; set; }
    }
}