// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbCasos
    {
        public TbCasos()
        {
            TbAcusadoPorCaso = new HashSet<TbAcusadoPorCaso>();
            TbEvidenciasPorCaso = new HashSet<TbEvidenciasPorCaso>();
            TbTestigosPorCaso = new HashSet<TbTestigosPorCaso>();
            TbVeredictos = new HashSet<TbVeredictos>();
        }

        public int CasoId { get; set; }
        public string CasoDescripcion { get; set; }
        public int? TicaId { get; set; }
        public int? CasoJuez { get; set; }
        public string CasoTipoDemandante { get; set; }
        public int? CasoDemandante { get; set; }
        public int? CasoAbogadoDemandante { get; set; }
        public int? CasoAbogadoDemandado { get; set; }
        public bool CasoAbierto { get; set; }
        public int CasoUsuCreacion { get; set; }
        public DateTime CasoFechaCreacion { get; set; }
        public int? CasoUsuModificacion { get; set; }
        public DateTime? CasoFechaModificacion { get; set; }
        public bool? CasoEstado { get; set; }

        public virtual TbAbogadosJueces CasoAbogadoDemandadoNavigation { get; set; }
        public virtual TbAbogadosJueces CasoAbogadoDemandanteNavigation { get; set; }
        public virtual TbAbogadosJueces CasoJuezNavigation { get; set; }
        public virtual TbUsuarios CasoUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios CasoUsuModificacionNavigation { get; set; }
        public virtual TbTiposdeCaso Tica { get; set; }
        public virtual ICollection<TbAcusadoPorCaso> TbAcusadoPorCaso { get; set; }
        public virtual ICollection<TbEvidenciasPorCaso> TbEvidenciasPorCaso { get; set; }
        public virtual ICollection<TbTestigosPorCaso> TbTestigosPorCaso { get; set; }
        public virtual ICollection<TbVeredictos> TbVeredictos { get; set; }
    }
}