// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbDetallesVeredictos
    {
        public int DeveId { get; set; }
        public int? VereId { get; set; }
        public bool? DeveEsInocente { get; set; }
        public bool? DeveEsculpable { get; set; }
        public string DeveTipoEmpresaCivil { get; set; }
        public int? DeveEmpresaCivil { get; set; }
        public int DeveUsuCreacion { get; set; }
        public DateTime DeveFechaCreacion { get; set; }
        public int? DeveUsuModificacion { get; set; }
        public DateTime? DeveFechaModificacion { get; set; }
        public bool? DeveEstado { get; set; }

        public virtual TbUsuarios DeveUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios DeveUsuModificacionNavigation { get; set; }
        public virtual TbVeredictos Vere { get; set; }
    }
}