// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbEvidenciasPorCaso
    {
        public int EvcaId { get; set; }
        public int? TievId { get; set; }
        public int? CasoId { get; set; }
        public string EvcaDescripcion { get; set; }
        public int EvcaUsuCreacion { get; set; }
        public DateTime EvcaFechaCreacion { get; set; }
        public int? EvcaUsuModificacion { get; set; }
        public DateTime? EvcaFechaModificacion { get; set; }
        public bool? EvcaEstado { get; set; }

        public virtual TbCasos Caso { get; set; }
        public virtual TbUsuarios EvcaUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios EvcaUsuModificacionNavigation { get; set; }
        public virtual TbTiposdeEvidencia Tiev { get; set; }
    }
}