// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbMunicipios
    {
        public TbMunicipios()
        {
            TbAbogadosJueces = new HashSet<TbAbogadosJueces>();
            TbCiviles = new HashSet<TbCiviles>();
            TbEmpleados = new HashSet<TbEmpleados>();
            TbEmpresas = new HashSet<TbEmpresas>();
        }

        public string MuniId { get; set; }
        public string MuniNombre { get; set; }
        public string DepaId { get; set; }
        public int MuniUsuCreacion { get; set; }
        public DateTime MuniFechaCreacion { get; set; }
        public int? MuniUsuModificacion { get; set; }
        public DateTime? MuniFechaModificacion { get; set; }
        public bool? MuniEstado { get; set; }

        public virtual TbDepartamentos Depa { get; set; }
        public virtual TbUsuarios MuniUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios MuniUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbAbogadosJueces> TbAbogadosJueces { get; set; }
        public virtual ICollection<TbCiviles> TbCiviles { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleados { get; set; }
        public virtual ICollection<TbEmpresas> TbEmpresas { get; set; }
    }
}