// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbPantallas
    {
        public TbPantallas()
        {
            TbRolesPorPantalla = new HashSet<TbRolesPorPantalla>();
        }

        public int PantId { get; set; }
        public string PantPantalla { get; set; }
        public string PantHref { get; set; }
        public string PantEsquema { get; set; }
        public string PantIcono { get; set; }
        public bool? PantEstado { get; set; }
        public int UsuaIdCreacion { get; set; }
        public DateTime? PantFechaCreacion { get; set; }
        public int? UsuaIdModificacion { get; set; }
        public DateTime? PantFechaModificacion { get; set; }

        public virtual TbUsuarios UsuaIdCreacionNavigation { get; set; }
        public virtual TbUsuarios UsuaIdModificacionNavigation { get; set; }
        public virtual ICollection<TbRolesPorPantalla> TbRolesPorPantalla { get; set; }
    }
}