// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbRolesPorPantalla
    {
        public int RopaId { get; set; }
        public int RoleId { get; set; }
        public int PantId { get; set; }
        public bool? RopaEstado { get; set; }
        public int UsuaIdCreacion { get; set; }
        public DateTime? RopaFechaCreacion { get; set; }
        public int? UsuaIdModificacion { get; set; }
        public DateTime? RopaFechaModificacion { get; set; }

        public virtual TbPantallas Pant { get; set; }
        public virtual TbRoles Role { get; set; }
        public virtual TbUsuarios UsuaIdCreacionNavigation { get; set; }
        public virtual TbUsuarios UsuaIdModificacionNavigation { get; set; }
    }
}