// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbRoles
    {
        public TbRoles()
        {
            TbRolesPorPantalla = new HashSet<TbRolesPorPantalla>();
            TbUsuarios = new HashSet<TbUsuarios>();
        }

        public int RoleId { get; set; }
        public string RoleNombre { get; set; }
        public string RoleDescripcion { get; set; }
        public bool? RoleEstado { get; set; }
        public int UsuaIdCreacion { get; set; }
        public DateTime? RoleFechaCreacion { get; set; }
        public int? UsuaIdModificacion { get; set; }
        public DateTime? RoleFechaModificacion { get; set; }

        public virtual TbUsuarios UsuaIdCreacionNavigation { get; set; }
        public virtual TbUsuarios UsuaIdModificacionNavigation { get; set; }
        public virtual ICollection<TbRolesPorPantalla> TbRolesPorPantalla { get; set; }
        public virtual ICollection<TbUsuarios> TbUsuarios { get; set; }
    }
}