// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbTestigosPorCaso
    {
        public int TecaId { get; set; }
        public int? CasoId { get; set; }
        public int? TecaTestigo { get; set; }
        public int TecaUsuCreacion { get; set; }
        public DateTime TecaFechaCreacion { get; set; }
        public int? TecaUsuModificacion { get; set; }
        public DateTime? TecaFechaModificacion { get; set; }
        public bool? TecaEstado { get; set; }

        public virtual TbCasos Caso { get; set; }
        public virtual TbCiviles TecaTestigoNavigation { get; set; }
        public virtual TbUsuarios TecaUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios TecaUsuModificacionNavigation { get; set; }
    }
}