// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbTiposdeEvidencia
    {
        public TbTiposdeEvidencia()
        {
            TbEvidenciasPorCaso = new HashSet<TbEvidenciasPorCaso>();
        }

        public int TievId { get; set; }
        public string TievNombre { get; set; }
        public string TievDescripcion { get; set; }
        public int TievUsuCreacion { get; set; }
        public DateTime TievFechaCreacion { get; set; }
        public int? TievUsuModificacion { get; set; }
        public DateTime? TievFechaModificacion { get; set; }
        public bool? TievEstado { get; set; }

        public virtual TbUsuarios TievUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios TievUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbEvidenciasPorCaso> TbEvidenciasPorCaso { get; set; }
    }
}