// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbTiposdeCaso
    {
        public TbTiposdeCaso()
        {
            TbCasos = new HashSet<TbCasos>();
        }

        public int TicaId { get; set; }
        public string TicaNombre { get; set; }
        public string TicaDescripcion { get; set; }
        public int TicaUsuCreacion { get; set; }
        public DateTime TicaFechaCreacion { get; set; }
        public int? TicaUsuModificacion { get; set; }
        public DateTime? TicaFechaModificacion { get; set; }
        public bool? TicaEstado { get; set; }

        public virtual TbUsuarios TicaUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios TicaUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbCasos> TbCasos { get; set; }
    }
}