// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbUsuarios
    {
        public TbUsuarios()
        {
            InverseUsuaIdCreacionNavigation = new HashSet<TbUsuarios>();
            InverseUsuaIdModificacionNavigation = new HashSet<TbUsuarios>();
            TbAbogadosJuecesAbjuUsuCreacionNavigation = new HashSet<TbAbogadosJueces>();
            TbAbogadosJuecesAbjuUsuModificacionNavigation = new HashSet<TbAbogadosJueces>();
            TbAcusadoPorCasoAcusUsuCreacionNavigation = new HashSet<TbAcusadoPorCaso>();
            TbAcusadoPorCasoAcusUsuModificacionNavigation = new HashSet<TbAcusadoPorCaso>();
            TbCargosCargUsuCreacionNavigation = new HashSet<TbCargos>();
            TbCargosCargUsuModificacionNavigation = new HashSet<TbCargos>();
            TbCasosCasoUsuCreacionNavigation = new HashSet<TbCasos>();
            TbCasosCasoUsuModificacionNavigation = new HashSet<TbCasos>();
            TbCivilesCiviUsuCreacionNavigation = new HashSet<TbCiviles>();
            TbCivilesCiviUsuModificacionNavigation = new HashSet<TbCiviles>();
            TbDepartamentosDepaUsuCreacionNavigation = new HashSet<TbDepartamentos>();
            TbDepartamentosDepaUsuModificacionNavigation = new HashSet<TbDepartamentos>();
            TbDetallesVeredictosDeveUsuCreacionNavigation = new HashSet<TbDetallesVeredictos>();
            TbDetallesVeredictosDeveUsuModificacionNavigation = new HashSet<TbDetallesVeredictos>();
            TbEmpleadosEmpeUsuCreacionNavigation = new HashSet<TbEmpleados>();
            TbEmpleadosEmpeUsuModificacionNavigation = new HashSet<TbEmpleados>();
            TbEmpresasEmsaUsuCreacionNavigation = new HashSet<TbEmpresas>();
            TbEmpresasEmsaUsuModificacionNavigation = new HashSet<TbEmpresas>();
            TbEvidenciasPorCasoEvcaUsuCreacionNavigation = new HashSet<TbEvidenciasPorCaso>();
            TbEvidenciasPorCasoEvcaUsuModificacionNavigation = new HashSet<TbEvidenciasPorCaso>();
            TbMunicipiosMuniUsuCreacionNavigation = new HashSet<TbMunicipios>();
            TbMunicipiosMuniUsuModificacionNavigation = new HashSet<TbMunicipios>();
            TbPantallasUsuaIdCreacionNavigation = new HashSet<TbPantallas>();
            TbPantallasUsuaIdModificacionNavigation = new HashSet<TbPantallas>();
            TbRolesPorPantallaUsuaIdCreacionNavigation = new HashSet<TbRolesPorPantalla>();
            TbRolesPorPantallaUsuaIdModificacionNavigation = new HashSet<TbRolesPorPantalla>();
            TbRolesUsuaIdCreacionNavigation = new HashSet<TbRoles>();
            TbRolesUsuaIdModificacionNavigation = new HashSet<TbRoles>();
            TbTestigosPorCasoTecaUsuCreacionNavigation = new HashSet<TbTestigosPorCaso>();
            TbTestigosPorCasoTecaUsuModificacionNavigation = new HashSet<TbTestigosPorCaso>();
            TbTiposdeCasoTicaUsuCreacionNavigation = new HashSet<TbTiposdeCaso>();
            TbTiposdeCasoTicaUsuModificacionNavigation = new HashSet<TbTiposdeCaso>();
            TbTiposdeEvidenciaTievUsuCreacionNavigation = new HashSet<TbTiposdeEvidencia>();
            TbTiposdeEvidenciaTievUsuModificacionNavigation = new HashSet<TbTiposdeEvidencia>();
            TbVeredictosVereUsuCreacionNavigation = new HashSet<TbVeredictos>();
            TbVeredictosVereUsuModificacionNavigation = new HashSet<TbVeredictos>();
        }

        public int UsuaId { get; set; }
        public string UsuaNombre { get; set; }
        public string UsuaClave { get; set; }
        public int? RoleId { get; set; }
        public int EmpeId { get; set; }
        public bool? UsuaEsAdmin { get; set; }
        public bool? UsuaEstado { get; set; }
        public int UsuaIdCreacion { get; set; }
        public DateTime? UsuaFechaCreacion { get; set; }
        public int? UsuaIdModificacion { get; set; }
        public DateTime? UsuaFechaModificacion { get; set; }

        public virtual TbRoles Role { get; set; }
        public virtual TbUsuarios UsuaIdCreacionNavigation { get; set; }
        public virtual TbUsuarios UsuaIdModificacionNavigation { get; set; }
        public virtual ICollection<TbUsuarios> InverseUsuaIdCreacionNavigation { get; set; }
        public virtual ICollection<TbUsuarios> InverseUsuaIdModificacionNavigation { get; set; }
        public virtual ICollection<TbAbogadosJueces> TbAbogadosJuecesAbjuUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbAbogadosJueces> TbAbogadosJuecesAbjuUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbAcusadoPorCaso> TbAcusadoPorCasoAcusUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbAcusadoPorCaso> TbAcusadoPorCasoAcusUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbCargos> TbCargosCargUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbCargos> TbCargosCargUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbCasos> TbCasosCasoUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbCasos> TbCasosCasoUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbCiviles> TbCivilesCiviUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbCiviles> TbCivilesCiviUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbDepartamentos> TbDepartamentosDepaUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbDepartamentos> TbDepartamentosDepaUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbDetallesVeredictos> TbDetallesVeredictosDeveUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbDetallesVeredictos> TbDetallesVeredictosDeveUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleadosEmpeUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbEmpleados> TbEmpleadosEmpeUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbEmpresas> TbEmpresasEmsaUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbEmpresas> TbEmpresasEmsaUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbEvidenciasPorCaso> TbEvidenciasPorCasoEvcaUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbEvidenciasPorCaso> TbEvidenciasPorCasoEvcaUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbMunicipios> TbMunicipiosMuniUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbMunicipios> TbMunicipiosMuniUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbPantallas> TbPantallasUsuaIdCreacionNavigation { get; set; }
        public virtual ICollection<TbPantallas> TbPantallasUsuaIdModificacionNavigation { get; set; }
        public virtual ICollection<TbRolesPorPantalla> TbRolesPorPantallaUsuaIdCreacionNavigation { get; set; }
        public virtual ICollection<TbRolesPorPantalla> TbRolesPorPantallaUsuaIdModificacionNavigation { get; set; }
        public virtual ICollection<TbRoles> TbRolesUsuaIdCreacionNavigation { get; set; }
        public virtual ICollection<TbRoles> TbRolesUsuaIdModificacionNavigation { get; set; }
        public virtual ICollection<TbTestigosPorCaso> TbTestigosPorCasoTecaUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbTestigosPorCaso> TbTestigosPorCasoTecaUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbTiposdeCaso> TbTiposdeCasoTicaUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbTiposdeCaso> TbTiposdeCasoTicaUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbTiposdeEvidencia> TbTiposdeEvidenciaTievUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbTiposdeEvidencia> TbTiposdeEvidenciaTievUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbVeredictos> TbVeredictosVereUsuCreacionNavigation { get; set; }
        public virtual ICollection<TbVeredictos> TbVeredictosVereUsuModificacionNavigation { get; set; }
    }
}