// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class TbVeredictos
    {
        public TbVeredictos()
        {
            TbDetallesVeredictos = new HashSet<TbDetallesVeredictos>();
        }

        public int VereId { get; set; }
        public int? CasoId { get; set; }
        public string VereDescripcion { get; set; }
        public int VereUsuCreacion { get; set; }
        public DateTime VereFechaCreacion { get; set; }
        public int? VereUsuModificacion { get; set; }
        public DateTime? VereFechaModificacion { get; set; }
        public bool? VereEstado { get; set; }

        public virtual TbCasos Caso { get; set; }
        public virtual TbUsuarios VereUsuCreacionNavigation { get; set; }
        public virtual TbUsuarios VereUsuModificacionNavigation { get; set; }
        public virtual ICollection<TbDetallesVeredictos> TbDetallesVeredictos { get; set; }
    }
}