// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class VwTbTiposdeCaso
    {
        public int TicaId { get; set; }
        public string TicaNombre { get; set; }
        public string TicaDescripcion { get; set; }
        public int TicaUsuCreacion { get; set; }
        public DateTime TicaFechaCreacion { get; set; }
        public int? TicaUsuModificacion { get; set; }
        public DateTime? TicaFechaModificacion { get; set; }
        public bool TicaEstado { get; set; }
    }
}