// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class VwTbEmpresas
    {
        public int EmsaId { get; set; }
        public string EmsaNombre { get; set; }
        public string EmsaRnt { get; set; }
        public string MuniId { get; set; }
        public string MuniNombre { get; set; }
        public string EmsaDireccion { get; set; }
        public string EmsaRepresentanteNombre { get; set; }
        public string EmsaRepresentanteDni { get; set; }
        public string EmsaRepresentanteTelefono { get; set; }
        public string EmsaRepresentanteSexo { get; set; }
        public int? EcivId { get; set; }
        public bool EmsaEsDemandante { get; set; }
        public bool EmsaEsAcusado { get; set; }
        public int EmsaUsuCreacion { get; set; }
        public DateTime EmsaFechaCreacion { get; set; }
        public int? EmsaUsuModificacion { get; set; }
        public DateTime? EmsaFechaModificacion { get; set; }
        public bool EmsaEstado { get; set; }
    }
}