// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class VwTbMunicipios
    {
        public string MuniId { get; set; }
        public string MuniNombre { get; set; }
        public string DepaId { get; set; }
        public string DepaNombre { get; set; }
        public int MuniUsuCreacion { get; set; }
        public string UserCreacion { get; set; }
        public DateTime MuniFechaCreacion { get; set; }
        public int? MuniUsuModificacion { get; set; }
        public string UserModificacion { get; set; }
        public DateTime? MuniFechaModificacion { get; set; }
        public bool MuniEstado { get; set; }
    }
}