// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class VwTbCargos
    {
        public int CargId { get; set; }
        public string CargDescripcion { get; set; }
        public int CargUsuCreacion { get; set; }
        public string UserCreacion { get; set; }
        public DateTime? CargFechaCreacion { get; set; }
        public int? CargUsuModificacion { get; set; }
        public string UserModificacion { get; set; }
        public DateTime? CargFechaModificacion { get; set; }
        public bool? CargEstado { get; set; }
    }
}