// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class VwTbAbogadosJueces
    {
        public int AbjuId { get; set; }
        public string AbjuDni { get; set; }
        public string AbjuNombres { get; set; }
        public string AbjuApellidos { get; set; }
        public string AbjuNombreCompleto { get; set; }
        public string AbjuSexo { get; set; }
        public string AbjuTelefono { get; set; }
        public string AbjuCorreoElectronico { get; set; }
        public DateTime AbjuFechaNacimiento { get; set; }
        public int EcivId { get; set; }
        public string EcivDescripcion { get; set; }
        public int CargId { get; set; }
        public string CargDescripcion { get; set; }
        public string MuniId { get; set; }
        public string MuniNombre { get; set; }
        public string DepaId { get; set; }
        public string DepaNombre { get; set; }
        public string AbjuDireccion { get; set; }
        public int AbjuUsuCreacion { get; set; }
        public string UserCreacion { get; set; }
        public DateTime AbjuFechaCreacion { get; set; }
        public int? AbjuUsuModificacion { get; set; }
        public string UserModificacion { get; set; }
        public DateTime? AbjuFechaModificacion { get; set; }
        public bool AbjuEstado { get; set; }
    }
}