// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class VwTbEstadosCiviles
    {
        public int EcivId { get; set; }
        public string EcivDescripcion { get; set; }
        public int EcivUsuCreacion { get; set; }
        public string UserCreacion { get; set; }
        public DateTime? EcivFechaCreacion { get; set; }
        public int? EcivUsuModificacion { get; set; }
        public string UserModificacion { get; set; }
        public DateTime? EcivFechaModificacion { get; set; }
        public bool? EcivEstado { get; set; }
    }
}