// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.DataAccess
{
    public partial class VwTbDepartamentos
    {
        public string DepaId { get; set; }
        public string DepaNombre { get; set; }
        public int DepaUsuCreacion { get; set; }
        public string UserCreacion { get; set; }
        public DateTime DepaFechaCreacion { get; set; }
        public int? DepaUsuModificacion { get; set; }
        public string UserModificacion { get; set; }
        public DateTime? DepaFechaModificacion { get; set; }
        public bool DepaEstado { get; set; }
    }
}