// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class tbAbogadosJueces
    {
        public tbAbogadosJueces()
        {
            tbCasosabju_IdAbogadoDemandadoNavigation = new HashSet<tbCasos>();
            tbCasosabju_IdAbogadoDemandanteNavigation = new HashSet<tbCasos>();
            tbCasosabju_IdJuezNavigation = new HashSet<tbCasos>();
        }

        public int abju_Id { get; set; }
        public string abju_DNI { get; set; }
        public string abju_Nombres { get; set; }
        public string abju_Apellidos { get; set; }
        public string abju_Sexo { get; set; }
        public string abju_Telefono { get; set; }
        public string abju_CorreoElectronico { get; set; }
        public DateTime abju_FechaNacimiento { get; set; }
        public int eciv_Id { get; set; }
        public int carg_Id { get; set; }
        public string muni_Id { get; set; }
        public string abju_Direccion { get; set; }
        public int abju_UsuCreacion { get; set; }
        public DateTime abju_FechaCreacion { get; set; }
        public int? abju_UsuModificacion { get; set; }
        public DateTime? abju_FechaModificacion { get; set; }
        public bool? abju_Estado { get; set; }

        public virtual tbUsuarios abju_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios abju_UsuModificacionNavigation { get; set; }
        public virtual tbCargos carg { get; set; }
        public virtual tbEstadosCiviles eciv { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbCasos> tbCasosabju_IdAbogadoDemandadoNavigation { get; set; }
        public virtual ICollection<tbCasos> tbCasosabju_IdAbogadoDemandanteNavigation { get; set; }
        public virtual ICollection<tbCasos> tbCasosabju_IdJuezNavigation { get; set; }
    }
}