// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class tbCasos
    {
        public tbCasos()
        {
            tbAcusadoPorCaso = new HashSet<tbAcusadoPorCaso>();
            tbEvidenciasPorCaso = new HashSet<tbEvidenciasPorCaso>();
            tbTestigosPorCaso = new HashSet<tbTestigosPorCaso>();
            tbVeredictos = new HashSet<tbVeredictos>();
        }

        public int caso_Id { get; set; }
        public string caso_descripcion { get; set; }
        public int? tica_Id { get; set; }
        public int? caso_Juez { get; set; }
        public string caso_TipoDemandante { get; set; }
        public int? caso_Demandante { get; set; }
        public int? caso_AbogadoDemandante { get; set; }
        public int? caso_AbogadoDemandado { get; set; }
        public bool caso_Abierto { get; set; }
        public int caso_UsuCreacion { get; set; }
        public DateTime caso_FechaCreacion { get; set; }
        public int? caso_UsuModificacion { get; set; }
        public DateTime? caso_FechaModificacion { get; set; }
        public bool? caso_Estado { get; set; }

        public virtual tbAbogadosJueces caso_AbogadoDemandadoNavigation { get; set; }
        public virtual tbAbogadosJueces caso_AbogadoDemandanteNavigation { get; set; }
        public virtual tbAbogadosJueces caso_JuezNavigation { get; set; }
        public virtual tbUsuarios caso_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios caso_UsuModificacionNavigation { get; set; }
        public virtual tbTiposdeCaso tica { get; set; }
        public virtual ICollection<tbAcusadoPorCaso> tbAcusadoPorCaso { get; set; }
        public virtual ICollection<tbEvidenciasPorCaso> tbEvidenciasPorCaso { get; set; }
        public virtual ICollection<tbTestigosPorCaso> tbTestigosPorCaso { get; set; }
        public virtual ICollection<tbVeredictos> tbVeredictos { get; set; }
    }
}