// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class tbPantallas
    {
        public tbPantallas()
        {
            tbRolesPorPantalla = new HashSet<tbRolesPorPantalla>();
        }

        public int pant_Id { get; set; }
        public string pant_Pantalla { get; set; }
        public string pant_Href { get; set; }
        public string pant_Esquema { get; set; }
        public bool? pant_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? pant_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? pant_FechaModificacion { get; set; }

        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbRolesPorPantalla> tbRolesPorPantalla { get; set; }
    }
}