// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbRolesPorPantalla = new HashSet<tbRolesPorPantalla>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int role_Id { get; set; }
        public string role_Nombre { get; set; }
        public string role_Descripcion { get; set; }
        public bool? role_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? role_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? role_FechaModificacion { get; set; }

        [NotMapped]
        public string usua_NombreCreacion { get; set; }

        [NotMapped]
        public string usua_NombreModificacion { get; set; }

        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbRolesPorPantalla> tbRolesPorPantalla { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}