// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class tbTiposdeEvidencia
    {
        public tbTiposdeEvidencia()
        {
            tbEvidenciasPorCaso = new HashSet<tbEvidenciasPorCaso>();
        }

        public int tiev_Id { get; set; }
        public string tiev_Nombre { get; set; }
        public string tiev_Descripcion { get; set; }
        public int tiev_UsuCreacion { get; set; }
        public DateTime tiev_FechaCreacion { get; set; }
        public int? tiev_UsuModificacion { get; set; }
        public DateTime? tiev_FechaModificacion { get; set; }
        public bool? tiev_Estado { get; set; }

        public virtual tbUsuarios tiev_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios tiev_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEvidenciasPorCaso> tbEvidenciasPorCaso { get; set; }
    }
}