// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_IdCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseusua_IdModificacionNavigation = new HashSet<tbUsuarios>();
            tbAbogadosJuecesabju_UsuCreacionNavigation = new HashSet<tbAbogadosJueces>();
            tbAbogadosJuecesabju_UsuModificacionNavigation = new HashSet<tbAbogadosJueces>();
            tbAcusadoPorCasoacus_UsuCreacionNavigation = new HashSet<tbAcusadoPorCaso>();
            tbAcusadoPorCasoacus_UsuModificacionNavigation = new HashSet<tbAcusadoPorCaso>();
            tbCargoscarg_UsuCreacionNavigation = new HashSet<tbCargos>();
            tbCargoscarg_UsuModificacionNavigation = new HashSet<tbCargos>();
            tbCasoscaso_UsuCreacionNavigation = new HashSet<tbCasos>();
            tbCasoscaso_UsuModificacionNavigation = new HashSet<tbCasos>();
            tbCivilescivi_UsuCreacionNavigation = new HashSet<tbCiviles>();
            tbCivilescivi_UsuModificacionNavigation = new HashSet<tbCiviles>();
            tbDepartamentosdepa_UsuCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdepa_UsuModificacionNavigation = new HashSet<tbDepartamentos>();
            tbDetallesVeredictosdeve_UsuCreacionNavigation = new HashSet<tbDetallesVeredictos>();
            tbDetallesVeredictosdeve_UsuModificacionNavigation = new HashSet<tbDetallesVeredictos>();
            tbEmpleadosempe_UsuCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempe_UsuModificacionNavigation = new HashSet<tbEmpleados>();
            tbEmpresasemsa_UsuCreacionNavigation = new HashSet<tbEmpresas>();
            tbEmpresasemsa_UsuModificacionNavigation = new HashSet<tbEmpresas>();
            tbEvidenciasPorCasoevca_UsuCreacionNavigation = new HashSet<tbEvidenciasPorCaso>();
            tbEvidenciasPorCasoevca_UsuModificacionNavigation = new HashSet<tbEvidenciasPorCaso>();
            tbMunicipiosmuni_UsuCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuModificacionNavigation = new HashSet<tbMunicipios>();
            tbPantallasusua_IdCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasusua_IdModificacionNavigation = new HashSet<tbPantallas>();
            tbRolesPorPantallausua_IdCreacionNavigation = new HashSet<tbRolesPorPantalla>();
            tbRolesPorPantallausua_IdModificacionNavigation = new HashSet<tbRolesPorPantalla>();
            tbRolesusua_IdCreacionNavigation = new HashSet<tbRoles>();
            tbRolesusua_IdModificacionNavigation = new HashSet<tbRoles>();
            tbTestigosPorCasoteca_UsuCreacionNavigation = new HashSet<tbTestigosPorCaso>();
            tbTestigosPorCasoteca_UsuModificacionNavigation = new HashSet<tbTestigosPorCaso>();
            tbTiposdeCasotica_UsuCreacionNavigation = new HashSet<tbTiposdeCaso>();
            tbTiposdeCasotica_UsuModificacionNavigation = new HashSet<tbTiposdeCaso>();
            tbTiposdeEvidenciatiev_UsuCreacionNavigation = new HashSet<tbTiposdeEvidencia>();
            tbTiposdeEvidenciatiev_UsuModificacionNavigation = new HashSet<tbTiposdeEvidencia>();
            tbVeredictosvere_UsuCreacionNavigation = new HashSet<tbVeredictos>();
            tbVeredictosvere_UsuModificacionNavigation = new HashSet<tbVeredictos>();
        }

        public int usua_Id { get; set; }
        public string usua_Nombre { get; set; }
        public string usua_Clave { get; set; }
        public int role_Id { get; set; }
        public int empe_Id { get; set; }
        public bool? usua_EsAdmin { get; set; }
        public bool? usua_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }

        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbAbogadosJueces> tbAbogadosJuecesabju_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbAbogadosJueces> tbAbogadosJuecesabju_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbAcusadoPorCaso> tbAcusadoPorCasoacus_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbAcusadoPorCaso> tbAcusadoPorCasoacus_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCasos> tbCasoscaso_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbCasos> tbCasoscaso_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCiviles> tbCivilescivi_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbCiviles> tbCivilescivi_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesVeredictos> tbDetallesVeredictosdeve_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbDetallesVeredictos> tbDetallesVeredictosdeve_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempe_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempe_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresasemsa_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresasemsa_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEvidenciasPorCaso> tbEvidenciasPorCasoevca_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEvidenciasPorCaso> tbEvidenciasPorCasoevca_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbRolesPorPantalla> tbRolesPorPantallausua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbRolesPorPantalla> tbRolesPorPantallausua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbTestigosPorCaso> tbTestigosPorCasoteca_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbTestigosPorCaso> tbTestigosPorCasoteca_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbTiposdeCaso> tbTiposdeCasotica_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbTiposdeCaso> tbTiposdeCasotica_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbTiposdeEvidencia> tbTiposdeEvidenciatiev_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbTiposdeEvidencia> tbTiposdeEvidenciatiev_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbVeredictos> tbVeredictosvere_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbVeredictos> tbVeredictosvere_UsuModificacionNavigation { get; set; }
    }
}