// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class tbVeredictos
    {
        public tbVeredictos()
        {
            tbDetallesVeredictos = new HashSet<tbDetallesVeredictos>();
        }

        public int vere_Id { get; set; }
        public int caso_Id { get; set; }
        public string vere_Descripcion { get; set; }
        public int vere_UsuCreacion { get; set; }
        public DateTime vere_FechaCreacion { get; set; }
        public int? vere_UsuModificacion { get; set; }
        public DateTime? vere_FechaModificacion { get; set; }
        public bool? vere_Estado { get; set; }

        public virtual tbCasos caso { get; set; }
        public virtual tbUsuarios vere_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios vere_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesVeredictos> tbDetallesVeredictos { get; set; }
    }
}