// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class VW_tbCiviles
    {
        public int civi_Id { get; set; }
        public string civi_DNI { get; set; }
        public string civi_Nombres { get; set; }
        public string civi_Apellidos { get; set; }
        public string civi_NombreCompleto { get; set; }
        public string civi_Sexo { get; set; }
        public string civi_Telefono { get; set; }
        public string civi_CorreoElectronico { get; set; }
        public DateTime civi_FechaNacimiento { get; set; }
        public int eciv_Id { get; set; }
        public string eciv_Descripcion { get; set; }
        public string muni_Id { get; set; }
        public string muni_Nombre { get; set; }
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public string civi_Direccion { get; set; }
        public int civi_UsuCreacion { get; set; }
        public string user_Creacion { get; set; }
        public DateTime civi_FechaCreacion { get; set; }
        public int? civi_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? civi_FechaModificacion { get; set; }
        public bool civi_Estado { get; set; }
    }
}