// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class VW_tbTiposdeCaso
    {
        public int tica_Id { get; set; }
        public string tica_Nombre { get; set; }
        public string tica_Descripcion { get; set; }
        public int tica_UsuCreacion { get; set; }
        public DateTime tica_FechaCreacion { get; set; }
        public int? tica_UsuModificacion { get; set; }
        public DateTime? tica_FechaModificacion { get; set; }
        public bool tica_Estado { get; set; }
    }
}