// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CasosLegales.Entities.Entities
{
    public partial class VW_tbCasos
    {
        public int caso_Id { get; set; }
        public string caso_Descripcion { get; set; }
        public int tica_Id { get; set; }
        public string tica_Nombre { get; set; }
        public int abju_IdJuez { get; set; }
        public string abju_AbogadoNombre { get; set; }
        public string caso_TipoDemandante { get; set; }
        public int caso_IdDemandante { get; set; }
        public string caso_DemandanteNombre { get; set; }
        public int abju_IdAbogadoDemandante { get; set; }
        public string abju_AbogadoDemandanteNombre { get; set; }
        public int abju_IdAbogadoDemandado { get; set; }
        public string abju_AbogadoDemandadoNombre { get; set; }
        public bool caso_Abierto { get; set; }
        public DateTime? caso_Fecha { get; set; }
        public bool? caso_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? caso_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? caso_FechaModificacion { get; set; }
    }
}